[package]
name = "baba_solver"
version = "0.1.0"
authors = ["Theo Barollet <theo.barollet@ensimag.fr>"]
edition = "2018"

[dependencies]
enum_primitive = "*"
variant_count = "*"
array-init = "0.1.0"
lazy_static = "1.4.0"
